# Streamlit Configuration
[server]
port = 8501
enableCORS = false

[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"

[client]
showErrorDetails = true

# Hide GitHub and Edit icons
[browser]
gatherUsageStats = false

[ui]
hideTopBar = false
