[browser]
gatherUsageStats = false
showErrorDetails = false

[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[ui]
hideTopBar = true
hideSidebarNav = true

[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
