# Streamlit Configuration
[server]
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200

[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"

[client]
showErrorDetails = false
toolbarMode = "minimal"

# Hide GitHub and Edit icons
[browser]
gatherUsageStats = false

[ui]
hideTopBar = false
