# Secrets configuration for Streamlit Cloud deployment
# Uncomment and configure the following for email functionality

[email]
SENDER_EMAIL = "your-email@gmail.com"
SENDER_PASSWORD = "your-app-password"

# Add other sensitive configuration here
[database]
# If using external database, add connection details here
# DB_URL = "your-database-url"
# DB_API_KEY = "your-api-key"
